manually replay all changes from revitalise branch (#12)

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -31,9 +31,11 @@ variables:
 
 .rpm-before-script: &rpm-before-script
   - |
+    set -x
     make get-sources
     make patch-for-rpm
     ls -la rpm
+    set +x
     echo "### before-script ##############################################"
     echo "CI_COMMIT_REF_NAME: ${CI_COMMIT_REF_NAME}"
     echo "CI_COMMIT_BRANCH:   ${CI_COMMIT_BRANCH}"
@@ -169,7 +171,7 @@ integration-tests:
     - .on-push-and-master
   inherit:
     variables: false
-  variables:    
+  variables:
     # these variables are actually transported to the other side,
     # even though inherit:variables:false
     HORRIBLE_MESS: marcus-hates-this
@@ -181,30 +183,70 @@ integration-tests:
     branch: main
     strategy: depend
 
-publish-debian-bookworm:
-  stage:publish
+publish-all:
+  extends:
+    - .repo-definition
+  stage: publish
+  image: "marcvs/test_ssh-oidc_debian-bookworm:1"
+
   script:
+    - !reference [.ssh-key-script]
     - |
       find results
-      echo "aaaaaaaaaa"
-      # Ensure package version is not yet in pre-release
-      (
-          cd results
-          for FILE in *rpm *deb; do 
-              ssh ${REPO_USER}@${REPO_HOST} "~/ci-voodoo/ci-tools/is-file-in-repo.sh " -t {$PUBLISH_RESULTS_REPO} -d ${DISTRO} -r ${RELEASE} -f ${FILE} || {
-                  echo "FILE DOES ALREADY EXIT"
-                  exit 1
-              }
+      (cd results
+          for DISTRO in *; do
+              for R in ${DISTRO}/*; do
+                  RELEASE=`basename $R`
+                  echo "DISTRO:  ${DISTRO}"
+                  echo "RELEASE: ${RELEASE}"
+                  echo "user@host: ${REPO_USER}@${REPO_HOST}"
+                  echo "PUBLISH_RESULTS_REPO: ${PUBLISH_RESULTS_REPO}"
+                  [ -z "$PUBLISH_RESULTS_REPO" ] && {
+                      echo "Error: PUBLISH_RESULTS_REPO is empty"
+                      exit 2
+                  }
+                  # Ensure package version is not yet in pre-release
+                  for FILE in ${DISTRO}/${RELEASE}/*rpm ${DISTRO}/${RELEASE}/*deb; do
+                      [ -e ${FILE} ] || continue
+                      echo "Handling file: $FILE"
+                      MD5SUM=`md5sum $FILE | cut -d ' ' -f 1`
+                      echo "MD5SUM: $MD5SUM - $FILE"
+                      ssh ${REPO_USER}@${REPO_HOST} "~/ci-voodoo/ci-tools/is-file-in-repo.sh  -t ${PUBLISH_RESULTS_REPO} -d ${DISTRO} -r ${RELEASE} -f `basename ${FILE}` -m ${MD5SUM}" || {
+                          echo "Error: File does already exist OR there was an ssh error"
+                          exit 1
+                      }
+                      echo "--------------------------------------------"
+                  done
+              done
           done
       )
 
-      echo "bbbbbbbbbbb"
-      # Copy files to new repo
+      # None of the files is already in the repo, or only with an existing
+      # md5sum.
+      # Therefore, we can now copy files to new repo, and sign it
+      echo "Uploading"
+      (cd results
+          for DISTRO in *; do
+              for R in ${DISTRO}/*; do
+                  RELEASE=`basename $R`
+                  for FILE in ${DISTRO}/${RELEASE}/*rpm ${DISTRO}/${RELEASE}/*deb; do
+                      [ -e ${FILE} ] || continue
+                      # this is strange, but will make the file location
+                      # be entirely be based on the remote ci-tools:
+                      cat ${FILE} | ssh ${REPO_USER}@${REPO_HOST} "~/ci-voodoo/ci-tools/place-file-in-repo.sh -t ${PUBLISH_RESULTS_REPO} -d ${DISTRO} -r ${RELEASE} -f `basename ${FILE}` -m ${MD5SUM}" || {
+                          echo "Error placing ${FILE} "
+                          exit 1
+                      }
+                      echo "--------------------------------------------"
+                  done
+                  ssh ${REPO_USER}@${REPO_HOST} "~/ci-voodoo/ci-tools/sign-repo.sh -t ${PUBLISH_RESULTS_REPO} -d ${DISTRO} -r ${RELEASE}"
+                  echo "============================================"
+              done
+          done
+      )
 
-      ${PUBLISH_RESULTS_REPO}
 
-      # Sign prerel repo
-      ssh ${REPO_USER}@${REPO_HOST} "~/ci-voodoo/ci-tools/sign-repo.sh -t ${PUBLISH_RESULTS_REPO} -d ${DISTRO} -r ${RELEASE}"
+      # Sign all involved prerel repos
 
 
 
